version: 0.2

phases:
  install:
    commands:
      - sudo apt update
      - cat /etc/*release
      - cp $CODEBUILD_SRC_DIR_toggless3/target/toggles-demo-service-0.0.1-SNAPSHOT.jar .
      - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
      - apt-get install -y curl && curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar xzv -C /usr/local/bin cf && cf install-plugin autopilot -f -r CF-Community
      - cf login -a $CF_API -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
  build:
    commands:
      - docker build -t filippo22/toggles-demo-service:latest .
      - docker images
      - docker push filippo22/toggles-demo-service:latest
  post_build:
    commands:
      - echo Build started on  `date`
      - cf push -f manifest-1-0-0-dev.yml
